pipeline:
  name: harness-tf-akamai-pipeline
  identifier: harnesstfakamaipipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: harnessgithubconnector
        build: <+input>
  stages:
    - stage:
        name: tf-docker
        identifier: tfdocker
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - stepGroup:
                  name: tf-step-group
                  identifier: tfstepgroup
                  steps:
                    - step:
                        type: ShellScript
                        name: ShellScript
                        identifier: ShellScript
                        spec:
                          shell: Bash
                          executionTarget: {}
                          source:
                            type: Inline
                            spec:
                              script: |-
                                echo "internal/prd/customer-success"
                                git log
                                tfc_workspace="path/to/workspace"
                          environmentVariables: []
                          outputVariables:
                            - name: tfc_workspace
                              type: String
                              value: tfc_workspace
                        timeout: 10m
                    - step:
                        type: TerraformCloudRun
                        name: TerraformCloudRun
                        identifier: TerraformCloudRun
                        spec:
                          runType: PlanOnly
                          runMessage: ""
                          spec:
                            organization: ___
                            workspace: <+execution.steps.tfstepgroup.steps.ShellScript.output.outputVariables.tfc_workspace>
                            variables: []
                            discardPendingRuns: true
                            targets: []
                            connectorRef: tfcharnessconnecter
                            provisionerIdentifier: _tfc_run
                            planType: Apply
                        timeout: 10m
        tags: {}
